### ISSUE TITLE
Community adoption of project

### ISSUE THREAD

**Issue by nmec** [google/jsonapi#180]
Hi there, really appreciate the work that you've put into this library and making it open source, we're using it exclusively for our internet facing endpoints. But I notice there hasn't been much activity by the maintainers for about a year, despite a number of open issues and pull requests with useful features.

Would the owners consider adding some contributors with merge permissions or perhaps allowing the community to adopt the project if they are no longer able to dedicate time to it?

Thanks once more, look forward to seeing the project moving again 🚤

**Comment by mfcochauxlaberge** [comment]
If I may shamelessly plug my own implementation, here it is: github.com/mfcochauxlaberge/jsonapi (if not, feel free to delete my comment). I was frustrated by the lack of good and maintained JSON:API implementations in Go and decided to make my own.

Pros:
- Active development since 2017 and still going
- A lot of features!
- API quite stable (v1.0.0 should come soon)
- Well tested

Cons:
- Very different approach from what this project and other projects do. Definitely not a drop-in replacement. If you use it in an already existing project, you will likely have to refactor.
- Needs a little bit of polishing
- No v1.0.0 yet (coming soon)

I want people to use the project and get feedback before I feel confident on committing to a stable API.

**Comment by aren55555** [comment]
I'm one of the two original authors, @shwoodard being the other.

We originally open sourced this out the Works With Nest program sometime in 2015. We had built an Ember.js frontend app that communicated with a Golang REST API (you can find the site on the [internet archives](https://web.archive.org/web/2019*/workswith.nest.com)). At the time there weren't any JSON API implementations for golang, so we wrote out own library and open sourced it hoping to provide value back to others looking to do the same.

Fast forward 5 years and the app has been turned down (sometime in late 2019). @shwoodard and I both don't work on this project anymore. In our new roles we also don't actively use this codebase (we live in a [protobuf](https://github.com/protocolbuffers/protobuf) world at Google), and as such we have neglected it. For that I'm sorry (I guess that's the Canadian in me coming out).

With that being said, this lib still works - even with current Go versions. As the [MIT license](https://github.com/google/jsonapi/blob/master/LICENSE) states, you are free to modify this, fork and improve it to your liking (or rethink, reimagine and rewrite it entirely like @mfcochauxlaberge has gone and done - props btw).

**Comment by tandr** [comment]
Fellas, I think it is worth a trouble to add something about the state of the project to a README.

**Comment by aren55555** [comment]
> Fellas, I think it is worth a trouble to add something about the state of the project to a README.

Done, there's a "No Maintenance Intended" badge on the Readme now.
