### ISSUE TITLE
map inside struct unmarshalling

### ISSUE THREAD

**Issue by kamilkoduo** [google/jsonapi#184]
**Please, help me with some workaround**

Adresses: https://github.com/google/jsonapi/issues/53 

A valid JSON API payload:
```
{
    "data": {
        "type": "cart_item",
        "id": "ci_id",
        "attributes": {
            "count": 1,
            "offer_id": "1",
            "offer_price": 400,
            "offer_title": {
                "en": "x",
                "ru": "f"
            }
        }
    }
}
```
is not being able to be unmarshalled into the type
```
type CartItem struct {
	CartItemID string            `jsonapi:"primary,cart_item"`
	OfferID    string            `jsonapi:"attr,offer_id"`
	OfferPrice float64           `jsonapi:"attr,offer_price"`
	OfferTitle map[string]string `jsonapi:"attr,offer_title"`
	Count      uint              `jsonapi:"attr,count"`
}
```
reporting errors:
```
data is not a jsonapi representation of '*api.CartItem'
```

One may respond that maps, as well as nested structures, are not supported by this library, but still, at least some workaround is needed.

**Comment by bogatyr285** [comment]
Greetings.
Your issue is a duplication of #53.
The solution is using map[string]interface{} for the representation of 'map' data type.
This happens because [under the hood](https://github.com/google/jsonapi/blob/master/request.go) library parses just built-in types like strings, int, pointers, etc. and there is no reason for writing unmarshalling for each data type if a user could use map[string]interface with type assertion.

**Comment by kamilkoduo** [comment]
@bogatyr285 
Thank you for the response. Your suggestion works, so I am closing the issue
